import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import {  Poppins, Rubik } from "next/font/google";
import Navbar from "@/components/NavBar";
const poppins = Poppins({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-poppins",
});
const rubik = Rubik({
  subsets: ["latin"],
  weight: "600",
  variable: "--font-rubik",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={`${poppins.variable} ${rubik.variable}`}>
      <main
        className={cn(
          "flex  relative  break-words h-dvh min-h-screen items-center justify-between pt-14 pb-4 px-40 max-md:p-4 bg-transparent max-sm:pt-20"
        )}
      >
        {/* NAVBAR ->  */}
        <Navbar />
        {children}
      </main>
    </body>
  </html>
  );
}
